services:
  airflow:
    image: my-airflow:latest
    volumes:
      - ./opt/airflow/dags:/opt/airflow/dags
      - ./opt/airflow/data:/opt/airflow/data
      - ./opt/airflow/env:/opt/airflow/env
      - ./opt/airflow/jobs:/opt/airflow/jobs
      - ./opt/airflow/logs:/opt/airflow/logs
      - ./opt/airflow/utils:/opt/airflow/utils
      - ./requirements.txt:/requirements.txt
    ports:
      - "8080:8080"
    command: bash -c "pip install -r /requirements.txt && airflow standalone"
