version: '3'
services:
  airflow:
    image: my-airflow:latest
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./jobs:/opt/airflow/jobs
      - ./jars:/opt/airflow/jars
      - ./env:/opt/airflow/env
      - ./data/Source:/opt/airflow/data/Source


    ports:
      - "8080:8080"
    command: airflow standalone